apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: myapp-secret
  namespace: external-secrets
spec:

  refreshInterval: 1m

  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore

  target:
    name: myapp-secret

  data:

  - secretKey: USERNAME
    remoteRef:
      key: /myapp/username

  - secretKey: PASSWORD
    remoteRef:
      key: /myapp/password